// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpxdyycecyznpzydsyxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1weGR5eWNlY3l6bnB6eWRzeXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDEwOTMsImV4cCI6MjA3MzI3NzA5M30.I0xpVxlRrfYbABuvdZBVNSH_f9AhD9VJLMyoQ6fHh1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});